openapi: 3.0.0
info:
  title: rb-concierge
  description: The Runblade CONCIERGE for the platform's interface, dashboards, reporting,
    etc
  license:
    name: Creative Commons Attribution-NonCommercial 4.0 International
    url: https://creativecommons.org/licenses/by-nc/4.0/legalcode
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/runblade/rb-concierge/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/runblade/concierge/1.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components:
  schemas:
    FAQ:
      type: object
      properties:
        id:
          type: string
          format: uuid
        question:
          type: string
          example: '["What type of ads are allowed on the Runblade platform?","What
            is Runblade''s vision?","What are Runblade''s values?"]'
        answer:
          type: string
          example: '["Runblade has a general policy disallowing adult content/items,
            alcohol, tobacco and gambling. Besides these all ads are subject to local
            laws and regulations and Runblade cedes authority to such higher powers.","Never
            worry about purchases. Ever.","Simplicity, Integrity, Practicality."]'
      description: General policies and information
