image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - deploy

cruncher_build:
  stage: build
  before_script:
    - "dotnet restore cruncher/docker/dotnet-api/DataShunt"
  script:
    - "dotnet build cruncher/docker/dotnet-api/DataShunt"

concierge_build:
  stage: build
  script:
    - "echo Concierge builds go here..."
  
negotiator_build:
  stage: build
  before_script:
    - "dotnet restore negotiator/SimulatedDevice"
  script:
    - "dotnet build negotiator/SimulatedDevice"

experiencer_build:
  stage: build
  script:
    - "echo Experiencer builds go here..."

cruncher_test:
  stage: test
  script: 
    - "echo Cruncher tests go here..."
 
concierge_test:
  stage: test
  script:
    - "echo Concierge tests go here..."
        
negotiator_test:
  stage: test
  script:
    - "dotnet test negotiator/SimulatedDevice.Tests"

experiencer_test:
  stage: test
  script:
    - "echo Experiencer test goes here..."