image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - deploy

experiencer_build:
  stage: build
  script:
    - "echo Experiencer build goes here..."

cruncher_build:
  stage: build
  before_script:
    - "dotnet restore cruncher/docker/dotnet-api/DataShunt"
  script:
    - "dotnet build cruncher/docker/dotnet-api/DataShunt"
  
negotiator_build:
  stage: build
  before_script:
    - "dotnet restore negotiator/SimulatedDevice"
  script:
    - "dotnet build negotiator/SimulatedDevice"

cruncher_test:
  stage: test
  script: 
    - "echo Cruncher tests go here..."
 
negotiator_test:
  stage: test
  script:
    - "dotnet test negotiator/SimulatedDevice.Tests"

experiencer_test:
  stage: test
  script:
    - "echo Experiencer test goes here..."